repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.6"
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy --explicit-package-bases
        language: system
        types: [python]
        args: ["--config-file", "mypy.ini"]
