services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env
    command: ["gunicorn", "src.config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4", "--timeout", "120"]

  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./static:/app/src/static
        - ./media:/app/src/media
      depends_on:
        - backend
      networks:
        - app_network

networks:
  app_network: