services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - ./staticfiles:/app/src/staticfiles
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env.prod
    command: ["gunicorn", "src.config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2", "--timeout", "120"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/src/staticfiles
      - ./media:/app/src/media
      - ./certs:/etc/letsencrypt:ro
      - ./certbot-www:/var/www/suncov/certbot
    depends_on:
      - backend
    networks:
      - app_network
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-www:/var/www/suncov/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
