services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network
    command: >
      bash -c "
        export PYTHONPATH=/app/src &&
        poetry install --no-root &&
        poetry run ruff check &&
        poetry run mypy src &&
        poetry run python manage.py migrate &&
        poetry run python manage.py loaddata fixtures/data.json &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "

  database:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
