# Generated by Django 5.1.6 on 2025-02-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partofspeech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partofspeech',
            options={'verbose_name': 'Part of Speech', 'verbose_name_plural': 'Parts of Speech'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='partofspeech',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_speech', to='partofspeech.theme', verbose_name='theme'),
        ),
    ]
