# Generated by Django 5.1.6 on 2025-02-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
