# Generated by Django 5.1.6 on 2025-02-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_remove_test_test_type_delete_testtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='slug',
        ),
    ]
