# Generated by Django 5.1.6 on 2025-02-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='dictation.theme', verbose_name='theme'),
        ),
    ]
