# Generated by Django 5.1.6 on 2025-02-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_alter_dictation_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictation',
            options={'verbose_name': 'Dictation', 'verbose_name_plural': 'Dictations'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='dictation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictations', to='dictation.theme', verbose_name='theme'),
        ),
    ]
