name: Linters

on:
  push:
    branches:
      - prod
      - dev
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - prod
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run Ruff
        run: poetry run ruff check

      - name: Run MyPy
        run: poetry run mypy src